---
# tasks file for roles/monitoring/grafana
- name: Install gpg
  ansible.builtin.apt:
    name: gnupg,software-properties-common
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Add gpg key
  ansible.builtin.apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: false

- name: Add repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    validate_certs: false

- name: Install grafana
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Change admin user
  ansible.builtin.lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: "{{ item.before }}"
    line: "{{ item.after }}"
  with_items:
    - { before: "^;admin_user = admin", after: "admin_user = {{ grafana_admin_user }}"}
    - { before: "^;admin_password = admin", after: "admin_password = {{ grafana_admin_password }}"}

- name: Start service grafana-server
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: true

- name: Wait for service up
  ansible.builtin.uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __grafana_result
  until: __grafana_result.status == 200
  retries: 120
  delay: 1

- name: Change admin password for grafana gui
  ansible.builtin.shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  register: __grafana_command_admin
