---
# handlers file for roles/vmagent
- name: Restart_vmagent
  ansible.builtin.systemd:
    name: vmagent
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart_vmalert
  ansible.builtin.systemd:
    name: vmalert
    state: restarted
    enabled: true
    daemon_reload: true
