---
# defaults file for roles/monitoring/grafana
grafana_admin_user: "unik"
grafana_admin_password: "123456"
grafana_prometheus_address: ""
grafana_datasources:
  - {name: "", type: "", url: "" }
grafana_dashboards:
  - { label: "", json: "" }
