---
# tasks file for roles/databases/postgresql/postgresql_single

- name: Add gpg key
  ansible.builtin.apt_key:
    url: "{{ postgresql_simple_repo_key }}"

- name: Add repository
  ansible.builtin.apt_repository:
    repo: "deb {{ postgresql_simple_repo_url }} {{ ansible_distribution_release }}-pgdg main"
    state: present

- name: Install postgresql and contrib
  ansible.builtin.apt:
    name: "postgresql={{ postgresql_simple_version_detail }},postgresql-contrib"
    state: present
    update_cache: true

- name: Create directory for postgresql data
  file:
    path: "{{ postgresql_simple_data_dir }}"
    state: directory
    mode: "0750"
    owner: postgres
    group: postgres
  when: postgresql_simple_data_dir != ""

- name: "Postgresql.conf change listen address"
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_simple_version_major }}/main/postgresql.conf"
    regex: "^listen_addresses = "
    insertafter: '^#listen_addresses '
    line: "listen_addresses = '{{ postgresql_simple_listen }}'"
    state: present
  notify: Restart_postgresql

- name: "Postgresql.conf change data directory"
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_simple_version_major }}/main/postgresql.conf"
    regex: "^data_directory = "
    insertafter: '^#data_directory '
    line: "data_directory = '{{ postgresql_simple_data_dir }}'"
    state: present
  when: postgresql_simple_data_dir != ""
  notify: Reconfigure_data_dir

- name: "Change postgres.conf to add include"
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_simple_version_major }}/main/postgresql.conf"
    regex: "^include 'postgresql.custom.conf'"
    insertafter: "^# Add settings for extensions here"
    line: "include 'postgresql.custom.conf'"
    state: present
  notify: Restart_postgresql

- name: "Add postgresql.custom.conf"
  template:
    src: postgresql.custom.conf.j2
    dest: /etc/postgresql/{{ postgresql_simple_version_major }}/main/postgresql.custom.conf
    mode: "0640"
    owner: postgres
    group: postgres
  notify: Restart_postgresql
  
- name: Add pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{ postgresql_simple_version_major }}/main/pg_hba.conf"
    mode: "0640"
    owner: postgres
    group: postgres
  notify: Reload_postgresql

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start postgresql
  service:
    name: postgresql
    state: started
    enabled: true
