- name: Monitoring # noqa role-name[path]
  become: true
  hosts: meta-app_monitoring
  vars:
    vmtools_vmagent_dir_disk_data: "/data"
    vmetrics_dir_disk_data: "/data"
    vmtools_vmalert_remote: vmetrics.service.infomaniak.consul
    vmtools_vmalert_grafana: grafana.service.infomaniak.consul
    grafana_admin_password: "{{ vault_grafana_admin_password }}"
    karma_alertmanager_uri: "http://alertmanager.service.infomaniak.consul:9093"
    grafana_prometheus_address: "vmetrics.service.infomaniak.consul:8428"
    grafana_datasources:
      - {name: "VictoriaMetrics", type: "prometheus", url: "http://{{ grafana_prometheus_address }}" }
    grafana_dashboards:
      - { label: "node-exporter", json: "https://raw.githubusercontent.com/rfrail3/grafana-dashboards/master/prometheus/node-exporter-full.json" }

    volumes_disks:
      - {disk: '/dev/sdb', path: '{{  vmtools_vmagent_dir_disk_data  }}'}
    consul_services:
      - {
        name: "vmagent",
        type: "http",
        check_target: "http://127.0.0.1:8429",
        interval: "20s",
        port: 8429
      }
      - {
        name: "vmetrics",
        type: "http",
        check_target: "http://127.0.0.1:8428",
        interval: "10s",
        port: 8428
      }
      - {
        name: "vmalert",
        type: "http",
        check_target: "http://127.0.0.1:8880",
        interval: "10s",
        port: 8880
      }
      - {
        name: "alertmanager",
        type: "http",
        check_target: "http://127.0.0.1:9093",
        interval: "10s",
        port: 9093
      }
      - {
        name: "karma",
        type: "http",
        check_target: "http://127.0.0.1:8080",
        interval: "10s",
        port: 8080
      }
      - {
        name: "grafana",
        type: "http",
        check_target: "http://127.0.0.1:3000",
        interval: "10s",
        port: 3000
      }
    vault_grafana_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32383364373064326530363238656165646361343266393761646137643932316662663139636335
          6534613034323136646631646535346634373961393762390a613030386163323032663262653230
          61373366333663313534626135623933643139666338373635303966633932646362623636393838
          3565643966626535640a323866343938663932383264656266336632663538376238376166316666
          3733



  roles:
    - volumes
    - monitoring/vmtools
    - monitoring/vmetrics
    - monitoring/alertmanager
    - monitoring/karma
    - monitoring/grafana
    - consul_services