- name: Monitoring
  become: true
  hosts: meta-app_monitoring
  vars:
    vmtools_vmagent_dir_disk_data: "/data"
    vmetrics_dir_disk_data: "/data"
    vmtools_vmalert_remote: vmetrics.service.infomaniak.consul
    vmtools_vmalert_grafana: grafana.service.infomaniak.consul
    volumes_disks:
      - {disk: '/dev/sdb', path: '{{  vmtools_vmagent_dir_disk_data  }}'}
    consul_services:
      - {
        name: "vmagent",
        type: "http",
        check_target: "http://127.0.0.1:8429",
        interval: "20s",
        port: 8429
      }
      - {
        name: "vmetrics",
        type: "http",
        check_target: "http://127.0.0.1:8428",
        interval: "10s",
        port: 8428
      }
      - {
        name: "vmalert",
        type: "http",
        check_target: "http://127.0.0.1:8880",
        interval: "10s",
        port: 8880
      }

  roles:
    - volumes
    - vmtools
    - vmetrics
    - consul_services
